# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [4]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

# Let's define a one-dimensional array 
!pip install numpy
import numpy as np
my_list = [10,  3,  4]
x = np.array(my_list)
x

array([10,  3,  4])

In [15]:
# Let's create a numpy array from the list "my_list"
from numpy import random
arr = random.rand(3,5)
arr

array([[0.87467538, 0.94536028, 0.99750097, 0.49978008, 0.17814179],
       [0.24773075, 0.95947145, 0.81908655, 0.65934656, 0.50735184],
       [0.36171148, 0.17836796, 0.95063456, 0.17279941, 0.92016016]])

In [16]:
y = random.uniform(-3, 3,size=(3,4))
y

array([[-0.88247167, -1.23805971,  0.90714092, -1.42097868],
       [ 2.05252052,  0.18859815, -1.03455189, -0.74754248],
       [ 0.50005094, -0.58969984, -2.15682946, -2.52356534]])

In [17]:
type(y)

numpy.ndarray

In [18]:
# Multi-dimensional (Matrix definition) 
my_arr = np.array([[2, 5, 8], [7, 3, 6]])
my_arr

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [19]:
my_arr = np.array([[3, 7, 9, 3], 
[4, 3, 2, 2]])
my_arr

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [21]:
# "rand()" uniform distribution between 0 and 1
x = random.rand(20)
x

array([0.13688965, 0.71362384, 0.68998493, 0.16631833, 0.2696853 ,
       0.40774821, 0.55528705, 0.13390261, 0.2416468 , 0.94252207,
       0.72484721, 0.93246009, 0.27888534, 0.79003495, 0.24024503,
       0.13082118, 0.89978452, 0.04339174, 0.13203309, 0.84022299])

In [22]:
# you can create a matrix of random number as well
y = random.rand(3,3)
y

array([[0.71078325, 0.89984434, 0.26138013],
       [0.33358144, 0.95990525, 0.99623395],
       [0.23280982, 0.05392934, 0.30362105]])

In [24]:
# "randint" is used to generate random integers between upper and lower bounds
a = random.randint(15, 16) # [15, 16)
a

15

In [29]:
# "randint" can be used to generate a certain number of random itegers as follows
x = random.randint(1, 100, 15)
x

array([83, 48, 76, 78,  7, 18, 95,  9,  7, 66, 79, 36, 68, 73, 24],
      dtype=int32)

In [30]:
# np.arange creates an evenly spaced values within a given interval
y = np.arange(1, 50, dtype=int)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [31]:
# create a diagonal of ones and zeros everywhere else
z = np.eye(7)
z

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [33]:
# Matrix of ones
w = np.ones((7,7))
w

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [34]:
# Array of zeros
w = np.zeros(7)
w

array([0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [37]:
x = int(input("Give me an integer="))
y = random.randint(0, x, (3, 10))
y

Give me an integer= 21


array([[ 9, 13,  7, 16, 18, 18,  2, 12,  8,  6],
       [ 9,  9,  7, 11, 11,  3,  9, 13,  7,  6],
       [ 4, 11,  3,  2,  9, 17, 19, 10,  2, 20]], dtype=int32)

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [41]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# Add 2 numpy arrays together
x = np.array([ 2,  4,  6,  8])
y = np.array([10, 12, 14, 16, 18])
z = np.concatenate((x, y))
z

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
x = x ** 2
x

array([ 4, 16, 36, 64])

In [46]:
xx = np.square(x)
xx

array([  16,  256, 1296, 4096])

In [47]:
y = np.sqrt(x)
y

array([2., 4., 6., 8.])

In [50]:
x = np.arange(1, 10)
z = np.exp(x)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [60]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(np.absolute(np.square(X) - np.square(Y)))
Z

array([ 7.48331477, 13.26649916, 19.59591794])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [61]:
x = np.array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [62]:
# Access specific index from the numpy array
x[0]

np.int64(3)

In [66]:
# Starting from the first index 0 up until and NOT including the last element
x[:3]

array([3, 5, 6])

In [67]:
# Broadcasting, altering several values in a numpy array at once
x[:4] = 7
x

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [68]:
# Let's define a two dimensional numpy array
y = np.array([[6, 9, 7, 1],
       [6, 5, 5, 5],
       [6, 9, 1, 8],
       [8, 9, 3, 1]])
y

array([[6, 9, 7, 1],
       [6, 5, 5, 5],
       [6, 9, 1, 8],
       [8, 9, 3, 1]])

In [69]:
# Get a row from a mtrix
y[0]

array([6, 9, 7, 1])

In [80]:
# Get one element
z = y[0][0]
print(type(z))
z.item()

<class 'numpy.int64'>


6

In [81]:
import decimal
print(type(z.item()))
z = decimal.Decimal(int(z))
z

<class 'int'>


Decimal('6')

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [95]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[2:4, :2] = 5
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [ 5,  5, -6, 90, 10],
       [ 5,  5, 34, 22, 12],
       [13, 24, 22, 32, 37]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [97]:
x = np.array([[4, 4, 3, 9, 6],
       [9, 9, 8, 9, 2],
       [4, 2, 1, 3, 3],
       [8, 1, 1, 6, 3],
       [1, 3, 6, 8, 8]])
x

array([[4, 4, 3, 9, 6],
       [9, 9, 8, 9, 2],
       [4, 2, 1, 3, 3],
       [8, 1, 1, 6, 3],
       [1, 3, 6, 8, 8]])

In [99]:
y = x[x >= 8]
y

array([9, 9, 9, 8, 9, 8, 8, 8])

In [100]:
# Obtain odd elements only
y = x[x%2 == 1]
y

array([3, 9, 9, 9, 9, 1, 3, 3, 1, 1, 3, 1, 3])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [105]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X < 0] = 0
X[X %2 == 1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [1]:
!pip install pandas
import pandas as pd

my_dict = {
    "Bank client ID":[111,222,333,444],
    "Bank Client Name":["Chanel","Steve", "Mitch", "Ryan"],	
    "Net worth [$]":[3500,29000,10000,2000], 
    "Years with bank":[3, 4, 9, 5]
}

df = pd.DataFrame(my_dict)
df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [53]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [107]:
# Let's obtain the data type 
type(df)

pandas.core.frame.DataFrame

In [2]:
# you can only view the first couple of rows using .head()
df.head(2)

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4

In [110]:
# you can only view the last couple of rows using .tail()
df.tail(1)

Bank client ID Bank Client Name  Net worth [$]  Years with bank
3             444             Ryan           2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [4]:
df.to_pickle("my_picle")

In [9]:
my_df = pd.read_pickle("my_picle")
my_df.describe()
my_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [62]:
# Pandas is used to read a csv file and store data in a DataFrame
# df = pd.read_csv(url)

In [10]:
!pip install lxml
tables = pd.read_html("https://www.livingin-canada.com/house-prices-canada.html#google_vignette")
print(len(tables))

2


In [13]:
# Read tabular data using read_html
tables[0][:-1]

City Average House Price 12 Month Change
0    Vancouver, BC          $1,036,000        + 2.63 %
1     Toronto, Ont            $870,000         +10.2 %
2      Ottawa, Ont            $479,000        + 15.4 %
3     Calgary, Alb            $410,000         – 1.5 %
4    Montreal, Que            $435,000         + 9.3 %
5      Halifax, NS            $331,000         + 3.6 %
6     Regina, Sask            $254,000         – 3.9 %
7  Fredericton, NB            $198,000         – 4.3 %

In [119]:
tables[1][:-1]

Province Average House Price 12 Month Change
0          British Columbia            $736,000         + 7.6 %
1                   Ontario            $594,000         – 3.2 %
2                   Alberta            $353,000         – 7.5 %
3                    Quebec            $340,000         + 7.6 %
4                  Manitoba            $295,000         – 1.4 %
5              Saskatchewan            $271,000         – 3.8 %
6               Nova Scotia            $266,000         + 3.5 %
7      Prince Edward Island            $243,000         + 3.0 %
8   Newfoundland / Labrador            $236,000         – 1.6 %
9             New Brunswick            $183,000         – 2.2 %
10         Canadian Average            $488,000         – 1.3 %

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [19]:
my_df = pd.read_html("https://www.ssa.gov/oact/progdata/nra.html")
assert len(my_df) > 0
if len(my_df) > 0:
    print(my_df[0])

                                        Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                               

# TASK #8: PANDAS OPERATIONS

In [20]:
# Let's define a dataframe as follows:
!pip install pandas
import pandas as pd

my_dict = {
    "Bank client ID":[111,222,333,444],
    "Bank Client Name":["Chanel","Steve", "Mitch", "Ryan"],	
    "Net worth [$]":[3500,29000,10000,2000], 
    "Years with bank":[3, 4, 9, 5]
}

df = pd.DataFrame(my_dict)
df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [21]:
# Pick certain rows that satisfy a certain criteria 
df[df["Years with bank"] > 4]

Bank client ID Bank Client Name  Net worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [26]:
df.loc[2:4]

Bank client ID Bank Client Name  Net worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [34]:
# Delete a column from a DataFrame
df.drop(columns=["Years with bank"])

Bank client ID Bank Client Name  Net worth [$]
0             111           Chanel           3500
1             222            Steve          29000
2             333            Mitch          10000
3             444             Ryan           2000

In [36]:
df.drop(columns=["Years with bank"], inplace=True)
df

Bank client ID Bank Client Name  Net worth [$]
0             111           Chanel           3500
1             222            Steve          29000
2             333            Mitch          10000
3             444             Ryan           2000

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [46]:
df["Net worth [$]"].sum()

np.int64(44500)

In [44]:
df.drop(columns=["Net worth [$]"])

Bank client ID Bank Client Name
0             111           Chanel
1             222            Steve
2             333            Mitch
3             444             Ryan

In [45]:
df[df["Net worth [$]"] > 5000]

Bank client ID Bank Client Name  Net worth [$]
1             222            Steve          29000
2             333            Mitch          10000

In [48]:
x = df[df["Net worth [$]"] > 5000]["Net worth [$]"].sum()
float(x)

39000.0

# TASK #9: PANDAS WITH FUNCTIONS

In [71]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [53]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def my_func(my_arg):
    """
    my +*= 0.2
    """
    return my_arg * 1.2

In [51]:
# You can apply a function to the DataFrame 
df['Net worth [$]'].apply(my_func)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [54]:
#hint len
df['Bank Client Name'].apply(len)	

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [55]:
def my_func(my_arg):
    return my_arg * 3 + 200

df['Net worth [$]'].apply(my_func)

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [57]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [59]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by=["Years with bank"])

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [61]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df.sort_values(by=["Years with bank"], inplace=True)

In [83]:
# Set inplace = True to ensure that change has taken place in memory 


In [62]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [90]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [63]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)
df1


A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [64]:
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)

df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [65]:
df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[8, 9, 10, 11],
)

df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [66]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [67]:
df4 = pd.DataFrame(
    {
        "E": ["A8", "A9", "A10", "A11"],
        "F": ["B8", "B9", "B10", "B11"],
        "G": ["C8", "C9", "C10", "C11"],
        "H": ["D8", "D9", "D10", "D11"],
    }
)

df4

E    F    G    H
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

In [69]:
pd.concat([df1, df4], axis=0)

A    B    C    D    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN   A8   B8   C8   D8
1  NaN  NaN  NaN  NaN   A9   B9   C9   D9
2  NaN  NaN  NaN  NaN  A10  B10  C10  D10
3  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [70]:
pd.concat([df1, df4], axis=1)

A   B   C   D    E    F    G    H
0  A0  B0  C0  D0   A8   B8   C8   D8
1  A1  B1  C1  D1   A9   B9   C9   D9
2  A2  B2  C2  D2  A10  B10  C10  D10
3  A3  B3  C3  D3  A11  B11  C11  D11

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

array([[[3, 7, 9, 3],
        [4, 3, 2, 2]]])

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [15]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

Please enter a positive integer value: 7


array([6, 5, 3, 5, 4, 2, 3, 3, 2, 1])

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [22]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [33]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [34]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [41]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [58]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

stock ticker symbols  price per share [$]  Number of stocks
0                 AAPL                 3500                 3
1                 AMZN                  200                 4
2                    T                   40                 9

In [59]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

0    10500
1      800
2      360
dtype: int64
Total portfolio value = 11660


MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [77]:
def networth_update(balance):
    return balance * 3 + 200 

In [78]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [79]:
results.sum()

134300

In [71]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5      Allen     Steve

In [72]:
# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2

Bank Client ID First Name  Last Name
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Bob
4             10      Holly   Michelle

In [73]:

# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary

Bank Client ID  Annual Salary [$/year]
0              1                   25000
1              2                   35000
2              3                   45000
3              4                   48000
4              5                   49000
5              6                   32000
6              7                   33000
7              8                   34000
8              9                   23000
9             10                   22000

In [74]:
# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all

Bank Client ID First Name  Last Name
0              1      Nancy        Rob
1              2       Alex        Ali
2              3       Shep     George
3              4        Max      Mitch
4              5      Allen      Steve
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Bob
4             10      Holly   Michelle

In [75]:
# Let's merge all data on 'Bank Client ID'
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df


Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000

In [76]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [78]:
bank_df_all = pd.concat([bank_df_all, new_client_df])
bank_df_all

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0             11         Ry        Aly                    1000
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [104]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [105]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000